/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: car-bus-msg.proto */

#ifndef PROTOBUF_C_car_2dbus_2dmsg_2eproto__INCLUDED
#define PROTOBUF_C_car_2dbus_2dmsg_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003003 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _CarBusMsgProto__InitFeatureRequest CarBusMsgProto__InitFeatureRequest;
typedef struct _CarBusMsgProto__InitFeatureResponse CarBusMsgProto__InitFeatureResponse;
typedef struct _CarBusMsgProto__ActivateFeatureRequest CarBusMsgProto__ActivateFeatureRequest;
typedef struct _CarBusMsgProto__ActivateFeatureResponse CarBusMsgProto__ActivateFeatureResponse;


/* --- enums --- */

typedef enum _CarBusMsgProto__RequestStatus {
  CAR_BUS_MSG_PROTO__REQUEST_STATUS__REQUEST_SUCCESS = 0,
  CAR_BUS_MSG_PROTO__REQUEST_STATUS__REQUEST_FAILED = 1
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(CAR_BUS_MSG_PROTO__REQUEST_STATUS)
} CarBusMsgProto__RequestStatus;

/* --- messages --- */

struct  _CarBusMsgProto__InitFeatureRequest
{
  ProtobufCMessage base;
  int32_t feature_uid;
};
#define CAR_BUS_MSG_PROTO__INIT_FEATURE_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&car_bus_msg_proto__init_feature_request__descriptor) \
    , 0 }


struct  _CarBusMsgProto__InitFeatureResponse
{
  ProtobufCMessage base;
  CarBusMsgProto__RequestStatus status;
  ProtobufCBinaryData req_nonce;
};
#define CAR_BUS_MSG_PROTO__INIT_FEATURE_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&car_bus_msg_proto__init_feature_response__descriptor) \
    , CAR_BUS_MSG_PROTO__REQUEST_STATUS__REQUEST_SUCCESS, {0,NULL} }


struct  _CarBusMsgProto__ActivateFeatureRequest
{
  ProtobufCMessage base;
  ProtobufCBinaryData auth_token;
  ProtobufCBinaryData token_iv;
  ProtobufCBinaryData token_tag;
};
#define CAR_BUS_MSG_PROTO__ACTIVATE_FEATURE_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&car_bus_msg_proto__activate_feature_request__descriptor) \
    , {0,NULL}, {0,NULL}, {0,NULL} }


struct  _CarBusMsgProto__ActivateFeatureResponse
{
  ProtobufCMessage base;
  CarBusMsgProto__RequestStatus status;
};
#define CAR_BUS_MSG_PROTO__ACTIVATE_FEATURE_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&car_bus_msg_proto__activate_feature_response__descriptor) \
    , CAR_BUS_MSG_PROTO__REQUEST_STATUS__REQUEST_SUCCESS }


/* CarBusMsgProto__InitFeatureRequest methods */
void   car_bus_msg_proto__init_feature_request__init
                     (CarBusMsgProto__InitFeatureRequest         *message);
size_t car_bus_msg_proto__init_feature_request__get_packed_size
                     (const CarBusMsgProto__InitFeatureRequest   *message);
size_t car_bus_msg_proto__init_feature_request__pack
                     (const CarBusMsgProto__InitFeatureRequest   *message,
                      uint8_t             *out);
size_t car_bus_msg_proto__init_feature_request__pack_to_buffer
                     (const CarBusMsgProto__InitFeatureRequest   *message,
                      ProtobufCBuffer     *buffer);
CarBusMsgProto__InitFeatureRequest *
       car_bus_msg_proto__init_feature_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   car_bus_msg_proto__init_feature_request__free_unpacked
                     (CarBusMsgProto__InitFeatureRequest *message,
                      ProtobufCAllocator *allocator);
/* CarBusMsgProto__InitFeatureResponse methods */
void   car_bus_msg_proto__init_feature_response__init
                     (CarBusMsgProto__InitFeatureResponse         *message);
size_t car_bus_msg_proto__init_feature_response__get_packed_size
                     (const CarBusMsgProto__InitFeatureResponse   *message);
size_t car_bus_msg_proto__init_feature_response__pack
                     (const CarBusMsgProto__InitFeatureResponse   *message,
                      uint8_t             *out);
size_t car_bus_msg_proto__init_feature_response__pack_to_buffer
                     (const CarBusMsgProto__InitFeatureResponse   *message,
                      ProtobufCBuffer     *buffer);
CarBusMsgProto__InitFeatureResponse *
       car_bus_msg_proto__init_feature_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   car_bus_msg_proto__init_feature_response__free_unpacked
                     (CarBusMsgProto__InitFeatureResponse *message,
                      ProtobufCAllocator *allocator);
/* CarBusMsgProto__ActivateFeatureRequest methods */
void   car_bus_msg_proto__activate_feature_request__init
                     (CarBusMsgProto__ActivateFeatureRequest         *message);
size_t car_bus_msg_proto__activate_feature_request__get_packed_size
                     (const CarBusMsgProto__ActivateFeatureRequest   *message);
size_t car_bus_msg_proto__activate_feature_request__pack
                     (const CarBusMsgProto__ActivateFeatureRequest   *message,
                      uint8_t             *out);
size_t car_bus_msg_proto__activate_feature_request__pack_to_buffer
                     (const CarBusMsgProto__ActivateFeatureRequest   *message,
                      ProtobufCBuffer     *buffer);
CarBusMsgProto__ActivateFeatureRequest *
       car_bus_msg_proto__activate_feature_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   car_bus_msg_proto__activate_feature_request__free_unpacked
                     (CarBusMsgProto__ActivateFeatureRequest *message,
                      ProtobufCAllocator *allocator);
/* CarBusMsgProto__ActivateFeatureResponse methods */
void   car_bus_msg_proto__activate_feature_response__init
                     (CarBusMsgProto__ActivateFeatureResponse         *message);
size_t car_bus_msg_proto__activate_feature_response__get_packed_size
                     (const CarBusMsgProto__ActivateFeatureResponse   *message);
size_t car_bus_msg_proto__activate_feature_response__pack
                     (const CarBusMsgProto__ActivateFeatureResponse   *message,
                      uint8_t             *out);
size_t car_bus_msg_proto__activate_feature_response__pack_to_buffer
                     (const CarBusMsgProto__ActivateFeatureResponse   *message,
                      ProtobufCBuffer     *buffer);
CarBusMsgProto__ActivateFeatureResponse *
       car_bus_msg_proto__activate_feature_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   car_bus_msg_proto__activate_feature_response__free_unpacked
                     (CarBusMsgProto__ActivateFeatureResponse *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*CarBusMsgProto__InitFeatureRequest_Closure)
                 (const CarBusMsgProto__InitFeatureRequest *message,
                  void *closure_data);
typedef void (*CarBusMsgProto__InitFeatureResponse_Closure)
                 (const CarBusMsgProto__InitFeatureResponse *message,
                  void *closure_data);
typedef void (*CarBusMsgProto__ActivateFeatureRequest_Closure)
                 (const CarBusMsgProto__ActivateFeatureRequest *message,
                  void *closure_data);
typedef void (*CarBusMsgProto__ActivateFeatureResponse_Closure)
                 (const CarBusMsgProto__ActivateFeatureResponse *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCEnumDescriptor    car_bus_msg_proto__request_status__descriptor;
extern const ProtobufCMessageDescriptor car_bus_msg_proto__init_feature_request__descriptor;
extern const ProtobufCMessageDescriptor car_bus_msg_proto__init_feature_response__descriptor;
extern const ProtobufCMessageDescriptor car_bus_msg_proto__activate_feature_request__descriptor;
extern const ProtobufCMessageDescriptor car_bus_msg_proto__activate_feature_response__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_car_2dbus_2dmsg_2eproto__INCLUDED */
