/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: car-bus-msg.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "car-bus-msg.pb-c.h"
void   car_bus_msg_proto__init_feature_request__init
                     (CarBusMsgProto__InitFeatureRequest         *message)
{
  static const CarBusMsgProto__InitFeatureRequest init_value = CAR_BUS_MSG_PROTO__INIT_FEATURE_REQUEST__INIT;
  *message = init_value;
}
size_t car_bus_msg_proto__init_feature_request__get_packed_size
                     (const CarBusMsgProto__InitFeatureRequest *message)
{
  assert(message->base.descriptor == &car_bus_msg_proto__init_feature_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t car_bus_msg_proto__init_feature_request__pack
                     (const CarBusMsgProto__InitFeatureRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &car_bus_msg_proto__init_feature_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t car_bus_msg_proto__init_feature_request__pack_to_buffer
                     (const CarBusMsgProto__InitFeatureRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &car_bus_msg_proto__init_feature_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CarBusMsgProto__InitFeatureRequest *
       car_bus_msg_proto__init_feature_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CarBusMsgProto__InitFeatureRequest *)
     protobuf_c_message_unpack (&car_bus_msg_proto__init_feature_request__descriptor,
                                allocator, len, data);
}
void   car_bus_msg_proto__init_feature_request__free_unpacked
                     (CarBusMsgProto__InitFeatureRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &car_bus_msg_proto__init_feature_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   car_bus_msg_proto__init_feature_response__init
                     (CarBusMsgProto__InitFeatureResponse         *message)
{
  static const CarBusMsgProto__InitFeatureResponse init_value = CAR_BUS_MSG_PROTO__INIT_FEATURE_RESPONSE__INIT;
  *message = init_value;
}
size_t car_bus_msg_proto__init_feature_response__get_packed_size
                     (const CarBusMsgProto__InitFeatureResponse *message)
{
  assert(message->base.descriptor == &car_bus_msg_proto__init_feature_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t car_bus_msg_proto__init_feature_response__pack
                     (const CarBusMsgProto__InitFeatureResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &car_bus_msg_proto__init_feature_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t car_bus_msg_proto__init_feature_response__pack_to_buffer
                     (const CarBusMsgProto__InitFeatureResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &car_bus_msg_proto__init_feature_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CarBusMsgProto__InitFeatureResponse *
       car_bus_msg_proto__init_feature_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CarBusMsgProto__InitFeatureResponse *)
     protobuf_c_message_unpack (&car_bus_msg_proto__init_feature_response__descriptor,
                                allocator, len, data);
}
void   car_bus_msg_proto__init_feature_response__free_unpacked
                     (CarBusMsgProto__InitFeatureResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &car_bus_msg_proto__init_feature_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   car_bus_msg_proto__activate_feature_request__init
                     (CarBusMsgProto__ActivateFeatureRequest         *message)
{
  static const CarBusMsgProto__ActivateFeatureRequest init_value = CAR_BUS_MSG_PROTO__ACTIVATE_FEATURE_REQUEST__INIT;
  *message = init_value;
}
size_t car_bus_msg_proto__activate_feature_request__get_packed_size
                     (const CarBusMsgProto__ActivateFeatureRequest *message)
{
  assert(message->base.descriptor == &car_bus_msg_proto__activate_feature_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t car_bus_msg_proto__activate_feature_request__pack
                     (const CarBusMsgProto__ActivateFeatureRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &car_bus_msg_proto__activate_feature_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t car_bus_msg_proto__activate_feature_request__pack_to_buffer
                     (const CarBusMsgProto__ActivateFeatureRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &car_bus_msg_proto__activate_feature_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CarBusMsgProto__ActivateFeatureRequest *
       car_bus_msg_proto__activate_feature_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CarBusMsgProto__ActivateFeatureRequest *)
     protobuf_c_message_unpack (&car_bus_msg_proto__activate_feature_request__descriptor,
                                allocator, len, data);
}
void   car_bus_msg_proto__activate_feature_request__free_unpacked
                     (CarBusMsgProto__ActivateFeatureRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &car_bus_msg_proto__activate_feature_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   car_bus_msg_proto__activate_feature_response__init
                     (CarBusMsgProto__ActivateFeatureResponse         *message)
{
  static const CarBusMsgProto__ActivateFeatureResponse init_value = CAR_BUS_MSG_PROTO__ACTIVATE_FEATURE_RESPONSE__INIT;
  *message = init_value;
}
size_t car_bus_msg_proto__activate_feature_response__get_packed_size
                     (const CarBusMsgProto__ActivateFeatureResponse *message)
{
  assert(message->base.descriptor == &car_bus_msg_proto__activate_feature_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t car_bus_msg_proto__activate_feature_response__pack
                     (const CarBusMsgProto__ActivateFeatureResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &car_bus_msg_proto__activate_feature_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t car_bus_msg_proto__activate_feature_response__pack_to_buffer
                     (const CarBusMsgProto__ActivateFeatureResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &car_bus_msg_proto__activate_feature_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CarBusMsgProto__ActivateFeatureResponse *
       car_bus_msg_proto__activate_feature_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CarBusMsgProto__ActivateFeatureResponse *)
     protobuf_c_message_unpack (&car_bus_msg_proto__activate_feature_response__descriptor,
                                allocator, len, data);
}
void   car_bus_msg_proto__activate_feature_response__free_unpacked
                     (CarBusMsgProto__ActivateFeatureResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &car_bus_msg_proto__activate_feature_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor car_bus_msg_proto__init_feature_request__field_descriptors[1] =
{
  {
    "feature_uid",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(CarBusMsgProto__InitFeatureRequest, feature_uid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned car_bus_msg_proto__init_feature_request__field_indices_by_name[] = {
  0,   /* field[0] = feature_uid */
};
static const ProtobufCIntRange car_bus_msg_proto__init_feature_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor car_bus_msg_proto__init_feature_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "car_bus_msg_proto.InitFeatureRequest",
  "InitFeatureRequest",
  "CarBusMsgProto__InitFeatureRequest",
  "car_bus_msg_proto",
  sizeof(CarBusMsgProto__InitFeatureRequest),
  1,
  car_bus_msg_proto__init_feature_request__field_descriptors,
  car_bus_msg_proto__init_feature_request__field_indices_by_name,
  1,  car_bus_msg_proto__init_feature_request__number_ranges,
  (ProtobufCMessageInit) car_bus_msg_proto__init_feature_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor car_bus_msg_proto__init_feature_response__field_descriptors[2] =
{
  {
    "status",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(CarBusMsgProto__InitFeatureResponse, status),
    &car_bus_msg_proto__request_status__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "req_nonce",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(CarBusMsgProto__InitFeatureResponse, req_nonce),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned car_bus_msg_proto__init_feature_response__field_indices_by_name[] = {
  1,   /* field[1] = req_nonce */
  0,   /* field[0] = status */
};
static const ProtobufCIntRange car_bus_msg_proto__init_feature_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor car_bus_msg_proto__init_feature_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "car_bus_msg_proto.InitFeatureResponse",
  "InitFeatureResponse",
  "CarBusMsgProto__InitFeatureResponse",
  "car_bus_msg_proto",
  sizeof(CarBusMsgProto__InitFeatureResponse),
  2,
  car_bus_msg_proto__init_feature_response__field_descriptors,
  car_bus_msg_proto__init_feature_response__field_indices_by_name,
  1,  car_bus_msg_proto__init_feature_response__number_ranges,
  (ProtobufCMessageInit) car_bus_msg_proto__init_feature_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor car_bus_msg_proto__activate_feature_request__field_descriptors[3] =
{
  {
    "auth_token",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(CarBusMsgProto__ActivateFeatureRequest, auth_token),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "token_iv",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(CarBusMsgProto__ActivateFeatureRequest, token_iv),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "token_tag",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(CarBusMsgProto__ActivateFeatureRequest, token_tag),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned car_bus_msg_proto__activate_feature_request__field_indices_by_name[] = {
  0,   /* field[0] = auth_token */
  1,   /* field[1] = token_iv */
  2,   /* field[2] = token_tag */
};
static const ProtobufCIntRange car_bus_msg_proto__activate_feature_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor car_bus_msg_proto__activate_feature_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "car_bus_msg_proto.ActivateFeatureRequest",
  "ActivateFeatureRequest",
  "CarBusMsgProto__ActivateFeatureRequest",
  "car_bus_msg_proto",
  sizeof(CarBusMsgProto__ActivateFeatureRequest),
  3,
  car_bus_msg_proto__activate_feature_request__field_descriptors,
  car_bus_msg_proto__activate_feature_request__field_indices_by_name,
  1,  car_bus_msg_proto__activate_feature_request__number_ranges,
  (ProtobufCMessageInit) car_bus_msg_proto__activate_feature_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor car_bus_msg_proto__activate_feature_response__field_descriptors[1] =
{
  {
    "status",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(CarBusMsgProto__ActivateFeatureResponse, status),
    &car_bus_msg_proto__request_status__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned car_bus_msg_proto__activate_feature_response__field_indices_by_name[] = {
  0,   /* field[0] = status */
};
static const ProtobufCIntRange car_bus_msg_proto__activate_feature_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor car_bus_msg_proto__activate_feature_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "car_bus_msg_proto.ActivateFeatureResponse",
  "ActivateFeatureResponse",
  "CarBusMsgProto__ActivateFeatureResponse",
  "car_bus_msg_proto",
  sizeof(CarBusMsgProto__ActivateFeatureResponse),
  1,
  car_bus_msg_proto__activate_feature_response__field_descriptors,
  car_bus_msg_proto__activate_feature_response__field_indices_by_name,
  1,  car_bus_msg_proto__activate_feature_response__number_ranges,
  (ProtobufCMessageInit) car_bus_msg_proto__activate_feature_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue car_bus_msg_proto__request_status__enum_values_by_number[2] =
{
  { "REQUEST_SUCCESS", "CAR_BUS_MSG_PROTO__REQUEST_STATUS__REQUEST_SUCCESS", 0 },
  { "REQUEST_FAILED", "CAR_BUS_MSG_PROTO__REQUEST_STATUS__REQUEST_FAILED", 1 },
};
static const ProtobufCIntRange car_bus_msg_proto__request_status__value_ranges[] = {
{0, 0},{0, 2}
};
static const ProtobufCEnumValueIndex car_bus_msg_proto__request_status__enum_values_by_name[2] =
{
  { "REQUEST_FAILED", 1 },
  { "REQUEST_SUCCESS", 0 },
};
const ProtobufCEnumDescriptor car_bus_msg_proto__request_status__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "car_bus_msg_proto.RequestStatus",
  "RequestStatus",
  "CarBusMsgProto__RequestStatus",
  "car_bus_msg_proto",
  2,
  car_bus_msg_proto__request_status__enum_values_by_number,
  2,
  car_bus_msg_proto__request_status__enum_values_by_name,
  1,
  car_bus_msg_proto__request_status__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
