/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: messages.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "messages.pb-c.h"
void   msg_proto__data_write_request__init
                     (MsgProto__DataWriteRequest         *message)
{
  static const MsgProto__DataWriteRequest init_value = MSG_PROTO__DATA_WRITE_REQUEST__INIT;
  *message = init_value;
}
size_t msg_proto__data_write_request__get_packed_size
                     (const MsgProto__DataWriteRequest *message)
{
  assert(message->base.descriptor == &msg_proto__data_write_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t msg_proto__data_write_request__pack
                     (const MsgProto__DataWriteRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &msg_proto__data_write_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t msg_proto__data_write_request__pack_to_buffer
                     (const MsgProto__DataWriteRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &msg_proto__data_write_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
MsgProto__DataWriteRequest *
       msg_proto__data_write_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (MsgProto__DataWriteRequest *)
     protobuf_c_message_unpack (&msg_proto__data_write_request__descriptor,
                                allocator, len, data);
}
void   msg_proto__data_write_request__free_unpacked
                     (MsgProto__DataWriteRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &msg_proto__data_write_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   msg_proto__data_write_response__init
                     (MsgProto__DataWriteResponse         *message)
{
  static const MsgProto__DataWriteResponse init_value = MSG_PROTO__DATA_WRITE_RESPONSE__INIT;
  *message = init_value;
}
size_t msg_proto__data_write_response__get_packed_size
                     (const MsgProto__DataWriteResponse *message)
{
  assert(message->base.descriptor == &msg_proto__data_write_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t msg_proto__data_write_response__pack
                     (const MsgProto__DataWriteResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &msg_proto__data_write_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t msg_proto__data_write_response__pack_to_buffer
                     (const MsgProto__DataWriteResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &msg_proto__data_write_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
MsgProto__DataWriteResponse *
       msg_proto__data_write_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (MsgProto__DataWriteResponse *)
     protobuf_c_message_unpack (&msg_proto__data_write_response__descriptor,
                                allocator, len, data);
}
void   msg_proto__data_write_response__free_unpacked
                     (MsgProto__DataWriteResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &msg_proto__data_write_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   msg_proto__data_read_request__init
                     (MsgProto__DataReadRequest         *message)
{
  static const MsgProto__DataReadRequest init_value = MSG_PROTO__DATA_READ_REQUEST__INIT;
  *message = init_value;
}
size_t msg_proto__data_read_request__get_packed_size
                     (const MsgProto__DataReadRequest *message)
{
  assert(message->base.descriptor == &msg_proto__data_read_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t msg_proto__data_read_request__pack
                     (const MsgProto__DataReadRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &msg_proto__data_read_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t msg_proto__data_read_request__pack_to_buffer
                     (const MsgProto__DataReadRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &msg_proto__data_read_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
MsgProto__DataReadRequest *
       msg_proto__data_read_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (MsgProto__DataReadRequest *)
     protobuf_c_message_unpack (&msg_proto__data_read_request__descriptor,
                                allocator, len, data);
}
void   msg_proto__data_read_request__free_unpacked
                     (MsgProto__DataReadRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &msg_proto__data_read_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   msg_proto__data_read_response__init
                     (MsgProto__DataReadResponse         *message)
{
  static const MsgProto__DataReadResponse init_value = MSG_PROTO__DATA_READ_RESPONSE__INIT;
  *message = init_value;
}
size_t msg_proto__data_read_response__get_packed_size
                     (const MsgProto__DataReadResponse *message)
{
  assert(message->base.descriptor == &msg_proto__data_read_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t msg_proto__data_read_response__pack
                     (const MsgProto__DataReadResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &msg_proto__data_read_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t msg_proto__data_read_response__pack_to_buffer
                     (const MsgProto__DataReadResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &msg_proto__data_read_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
MsgProto__DataReadResponse *
       msg_proto__data_read_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (MsgProto__DataReadResponse *)
     protobuf_c_message_unpack (&msg_proto__data_read_response__descriptor,
                                allocator, len, data);
}
void   msg_proto__data_read_response__free_unpacked
                     (MsgProto__DataReadResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &msg_proto__data_read_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor msg_proto__data_write_request__field_descriptors[2] =
{
  {
    "storage_key",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(MsgProto__DataWriteRequest, storage_key),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value_blob",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(MsgProto__DataWriteRequest, value_blob),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned msg_proto__data_write_request__field_indices_by_name[] = {
  0,   /* field[0] = storage_key */
  1,   /* field[1] = value_blob */
};
static const ProtobufCIntRange msg_proto__data_write_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor msg_proto__data_write_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "msg_proto.DataWriteRequest",
  "DataWriteRequest",
  "MsgProto__DataWriteRequest",
  "msg_proto",
  sizeof(MsgProto__DataWriteRequest),
  2,
  msg_proto__data_write_request__field_descriptors,
  msg_proto__data_write_request__field_indices_by_name,
  1,  msg_proto__data_write_request__number_ranges,
  (ProtobufCMessageInit) msg_proto__data_write_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor msg_proto__data_write_response__field_descriptors[1] =
{
  {
    "status",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(MsgProto__DataWriteResponse, status),
    &msg_proto__request_status__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned msg_proto__data_write_response__field_indices_by_name[] = {
  0,   /* field[0] = status */
};
static const ProtobufCIntRange msg_proto__data_write_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor msg_proto__data_write_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "msg_proto.DataWriteResponse",
  "DataWriteResponse",
  "MsgProto__DataWriteResponse",
  "msg_proto",
  sizeof(MsgProto__DataWriteResponse),
  1,
  msg_proto__data_write_response__field_descriptors,
  msg_proto__data_write_response__field_indices_by_name,
  1,  msg_proto__data_write_response__number_ranges,
  (ProtobufCMessageInit) msg_proto__data_write_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor msg_proto__data_read_request__field_descriptors[1] =
{
  {
    "storage_key",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(MsgProto__DataReadRequest, storage_key),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned msg_proto__data_read_request__field_indices_by_name[] = {
  0,   /* field[0] = storage_key */
};
static const ProtobufCIntRange msg_proto__data_read_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor msg_proto__data_read_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "msg_proto.DataReadRequest",
  "DataReadRequest",
  "MsgProto__DataReadRequest",
  "msg_proto",
  sizeof(MsgProto__DataReadRequest),
  1,
  msg_proto__data_read_request__field_descriptors,
  msg_proto__data_read_request__field_indices_by_name,
  1,  msg_proto__data_read_request__number_ranges,
  (ProtobufCMessageInit) msg_proto__data_read_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor msg_proto__data_read_response__field_descriptors[2] =
{
  {
    "status",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(MsgProto__DataReadResponse, status),
    &msg_proto__request_status__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value_blob",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(MsgProto__DataReadResponse, value_blob),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned msg_proto__data_read_response__field_indices_by_name[] = {
  0,   /* field[0] = status */
  1,   /* field[1] = value_blob */
};
static const ProtobufCIntRange msg_proto__data_read_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor msg_proto__data_read_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "msg_proto.DataReadResponse",
  "DataReadResponse",
  "MsgProto__DataReadResponse",
  "msg_proto",
  sizeof(MsgProto__DataReadResponse),
  2,
  msg_proto__data_read_response__field_descriptors,
  msg_proto__data_read_response__field_indices_by_name,
  1,  msg_proto__data_read_response__number_ranges,
  (ProtobufCMessageInit) msg_proto__data_read_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue msg_proto__request_status__enum_values_by_number[2] =
{
  { "REQUEST_SUCCESS", "MSG_PROTO__REQUEST_STATUS__REQUEST_SUCCESS", 0 },
  { "REQUEST_FAILED", "MSG_PROTO__REQUEST_STATUS__REQUEST_FAILED", 1 },
};
static const ProtobufCIntRange msg_proto__request_status__value_ranges[] = {
{0, 0},{0, 2}
};
static const ProtobufCEnumValueIndex msg_proto__request_status__enum_values_by_name[2] =
{
  { "REQUEST_FAILED", 1 },
  { "REQUEST_SUCCESS", 0 },
};
const ProtobufCEnumDescriptor msg_proto__request_status__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "msg_proto.RequestStatus",
  "RequestStatus",
  "MsgProto__RequestStatus",
  "msg_proto",
  2,
  msg_proto__request_status__enum_values_by_number,
  2,
  msg_proto__request_status__enum_values_by_name,
  1,
  msg_proto__request_status__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
