/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: messages.proto */

#ifndef PROTOBUF_C_messages_2eproto__INCLUDED
#define PROTOBUF_C_messages_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003003 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _MsgProto__DataWriteRequest MsgProto__DataWriteRequest;
typedef struct _MsgProto__DataWriteResponse MsgProto__DataWriteResponse;
typedef struct _MsgProto__DataReadRequest MsgProto__DataReadRequest;
typedef struct _MsgProto__DataReadResponse MsgProto__DataReadResponse;


/* --- enums --- */

typedef enum _MsgProto__RequestStatus {
  MSG_PROTO__REQUEST_STATUS__REQUEST_SUCCESS = 0,
  MSG_PROTO__REQUEST_STATUS__REQUEST_FAILED = 1
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(MSG_PROTO__REQUEST_STATUS)
} MsgProto__RequestStatus;

/* --- messages --- */

struct  _MsgProto__DataWriteRequest
{
  ProtobufCMessage base;
  ProtobufCBinaryData storage_key;
  ProtobufCBinaryData value_blob;
};
#define MSG_PROTO__DATA_WRITE_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&msg_proto__data_write_request__descriptor) \
    , {0,NULL}, {0,NULL} }


struct  _MsgProto__DataWriteResponse
{
  ProtobufCMessage base;
  MsgProto__RequestStatus status;
};
#define MSG_PROTO__DATA_WRITE_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&msg_proto__data_write_response__descriptor) \
    , MSG_PROTO__REQUEST_STATUS__REQUEST_SUCCESS }


struct  _MsgProto__DataReadRequest
{
  ProtobufCMessage base;
  ProtobufCBinaryData storage_key;
};
#define MSG_PROTO__DATA_READ_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&msg_proto__data_read_request__descriptor) \
    , {0,NULL} }


struct  _MsgProto__DataReadResponse
{
  ProtobufCMessage base;
  MsgProto__RequestStatus status;
  ProtobufCBinaryData value_blob;
};
#define MSG_PROTO__DATA_READ_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&msg_proto__data_read_response__descriptor) \
    , MSG_PROTO__REQUEST_STATUS__REQUEST_SUCCESS, {0,NULL} }


/* MsgProto__DataWriteRequest methods */
void   msg_proto__data_write_request__init
                     (MsgProto__DataWriteRequest         *message);
size_t msg_proto__data_write_request__get_packed_size
                     (const MsgProto__DataWriteRequest   *message);
size_t msg_proto__data_write_request__pack
                     (const MsgProto__DataWriteRequest   *message,
                      uint8_t             *out);
size_t msg_proto__data_write_request__pack_to_buffer
                     (const MsgProto__DataWriteRequest   *message,
                      ProtobufCBuffer     *buffer);
MsgProto__DataWriteRequest *
       msg_proto__data_write_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   msg_proto__data_write_request__free_unpacked
                     (MsgProto__DataWriteRequest *message,
                      ProtobufCAllocator *allocator);
/* MsgProto__DataWriteResponse methods */
void   msg_proto__data_write_response__init
                     (MsgProto__DataWriteResponse         *message);
size_t msg_proto__data_write_response__get_packed_size
                     (const MsgProto__DataWriteResponse   *message);
size_t msg_proto__data_write_response__pack
                     (const MsgProto__DataWriteResponse   *message,
                      uint8_t             *out);
size_t msg_proto__data_write_response__pack_to_buffer
                     (const MsgProto__DataWriteResponse   *message,
                      ProtobufCBuffer     *buffer);
MsgProto__DataWriteResponse *
       msg_proto__data_write_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   msg_proto__data_write_response__free_unpacked
                     (MsgProto__DataWriteResponse *message,
                      ProtobufCAllocator *allocator);
/* MsgProto__DataReadRequest methods */
void   msg_proto__data_read_request__init
                     (MsgProto__DataReadRequest         *message);
size_t msg_proto__data_read_request__get_packed_size
                     (const MsgProto__DataReadRequest   *message);
size_t msg_proto__data_read_request__pack
                     (const MsgProto__DataReadRequest   *message,
                      uint8_t             *out);
size_t msg_proto__data_read_request__pack_to_buffer
                     (const MsgProto__DataReadRequest   *message,
                      ProtobufCBuffer     *buffer);
MsgProto__DataReadRequest *
       msg_proto__data_read_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   msg_proto__data_read_request__free_unpacked
                     (MsgProto__DataReadRequest *message,
                      ProtobufCAllocator *allocator);
/* MsgProto__DataReadResponse methods */
void   msg_proto__data_read_response__init
                     (MsgProto__DataReadResponse         *message);
size_t msg_proto__data_read_response__get_packed_size
                     (const MsgProto__DataReadResponse   *message);
size_t msg_proto__data_read_response__pack
                     (const MsgProto__DataReadResponse   *message,
                      uint8_t             *out);
size_t msg_proto__data_read_response__pack_to_buffer
                     (const MsgProto__DataReadResponse   *message,
                      ProtobufCBuffer     *buffer);
MsgProto__DataReadResponse *
       msg_proto__data_read_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   msg_proto__data_read_response__free_unpacked
                     (MsgProto__DataReadResponse *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*MsgProto__DataWriteRequest_Closure)
                 (const MsgProto__DataWriteRequest *message,
                  void *closure_data);
typedef void (*MsgProto__DataWriteResponse_Closure)
                 (const MsgProto__DataWriteResponse *message,
                  void *closure_data);
typedef void (*MsgProto__DataReadRequest_Closure)
                 (const MsgProto__DataReadRequest *message,
                  void *closure_data);
typedef void (*MsgProto__DataReadResponse_Closure)
                 (const MsgProto__DataReadResponse *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCEnumDescriptor    msg_proto__request_status__descriptor;
extern const ProtobufCMessageDescriptor msg_proto__data_write_request__descriptor;
extern const ProtobufCMessageDescriptor msg_proto__data_write_response__descriptor;
extern const ProtobufCMessageDescriptor msg_proto__data_read_request__descriptor;
extern const ProtobufCMessageDescriptor msg_proto__data_read_response__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_messages_2eproto__INCLUDED */
